services:
    reuse_mart_franken:
        container_name: reuse_mart_franken
        image: image_reuse_mart_franken
        build: 
          dockerfile: worker.Dockerfile
          context: .
        ports:
            - 8000:8000
        env_file:
            - .env
